version: '3'


services:
  web:
    image: ${REGISTRY_LOCATION}/web:latest
    ports: 
      - "${WEB_PORT}:8080"
    environment:
      - BASE_URL=${BASE_URL}

  organizerserver:
    image: ${REGISTRY_LOCATION}/organizerserver:latest
    ports:
      - "${ORGANIZER_SERVER_PORT}:8080"
    environment:
      - OBSIDIAN_VAULT_REPO_LOCATION=/app/vault
    volumes:
      - ${VAULT_LOCATION}:/app/vault

  updater:
    image: ${REGISTRY_LOCATION}/updater:latest
    environment:
      - OBSIDIAN_VAULT_REPO_LOCATION=/app/vault
      - USERNAME=${GUSERNAME}
      - PASSWORD=${GPASSWORD}
      - TOKEN=${GTOKEN}
      - OUTPUT_PATH=/app/output
    volumes:
      - ${VAULT_LOCATION}=/app/vault
