version: '3'

services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    networks:
      - obsidian_network
    volumes:
      - $OBSIDIAN_VAULTS:/vaults
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver

  organizerserver:
    image: happydance/organizerserver:latest
    environment:
      - OBSIDIAN_VAULT_REPO_LOCATION=/app/vault
    volumes:
      - $OBSIDIAN_VAULTS/SyncedVault/Organizer:/app/vault
    networks:
      - obsidian_network

  updater:
    image: happydance/updater:latest
    environment:
      - VAULT_LOCATION=/app/vault
      - USERNAME=$GUSERNAME
      - PASSWORD=$GPASSWORD
      - TOKEN=$GTOKEN
      - OUTPUT_PATH=/app/output
    volumes:
      - $OBSIDIAN_VAULTS/SyncedVault:/app/vault

  # Updated agent-server service with .env file
  agent-server:
    image: happydance/agent-server:latest
    restart: unless-stopped
    environment:
      - API_URL=https://api.openai.com/v1/chat/completions
      - LLM_TYPE=ChatGPT
      - ORGANIZER_SERVER_URL=http://organizerserver:8080
      - REST_ADDRESS=$AGENT_SERVER_REST_ADDRESS
      - REST_PORT=$AGENT_SERVER_REST_PORT
      - API_KEY=$OPENAI_API_KEY
    networks:
      - obsidian_network

  nginx_proxy_manager:
    image: 'happydance/nginx:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    networks:
      - obsidian_network
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - AGENT_SERVER_PORT=$AGENT_SERVER_REST_PORT
    volumes:
      - ./custom_server.conf:/etc/nginx/conf.d/custom_server.conf
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./npm/log:/var/log/nginx
      - ./dev/.htpasswd:/etc/nginx/.htpasswd 


networks:
  obsidian_network:

