services:
  organizerserver:
    image: happydance/organizerserver:latest
    environment:
      - BASE_GIT_REPO_LOCATION=$BASE_GIT_REPO_LOCATION_CONTAINER
      - GIT_TOKEN=$GIT_TOKEN
      - GIT_USER=$GIT_USER
      - NOTE_BASE_LOCATION=$NOTE_BASE_LOCATION_CONTAINER
      - OBSIDIAN_VAULT_REPO_LOCATION=$OBSIDIAN_VAULT_REPO_LOCATION_CONTAINER
    volumes:
      - $OBSIDIAN_VAULT_LOCATION_HOST:$OBSIDIAN_VAULT_LOCATION_CONTAINER
      - ~/.ssh:/root/.ssh:ro
    networks:
      - obsidian_network

  updater:
    image: happydance/updater:latest
    environment:
      - VAULT_LOCATION=/app/vault
      - USERNAME=$GUSERNAME
      - PASSWORD=$GPASSWORD
      - TOKEN=$GTOKEN
      - OUTPUT_PATH=/app/output
    volumes:
      - $OBSIDIAN_VAULTS:/app/vault

  agent-server:
    image: registry.alanhoangnguyen.com/admin/agent-server:${AGENT_VERSION:-latest}
    restart: unless-stopped
    environment:
      - ORGANIZER_SERVER_URL=http://organizerserver:8080
      - REST_ADDRESS=$AGENT_SERVER_REST_ADDRESS
      - REST_PORT=$AGENT_SERVER_REST_PORT
      - FIREWORKS_API_KEY=$FIREWORKS_API_KEY
      - SCHEDULER_URL=http://scheduler:8080
      - LLM_LOG_FILE=/app/logs/llm.log
      - GENERAL_LOG_FILE=/app/logs/general.log
      - LOG_LEVEL=DEBUG
      - USER_ENCRYPTION_KEY=$USER_ENCRYPTION_KEY
      - USER_DATA_PATH=/app/user
      - FIREBASE_SERVICE_ACCOUNT_KEY_LOCATION=/app/firebase/FirebaseServiceAccountKey.json
      - WS_HOST=$WS_HOST
      - WS_PORT=$WS_PORT
      - SPEECH_PAUSE_TIMEOUT_SEC=$SPEECH_PAUSE_TIMEOUT_SEC
      - UNIFIED_STARTUP=$UNIFIED_STARTUP
      - USE_MOCK_AGENT=$USE_MOCK_AGENT
      - MODEL_COMMAND_PARSER=$MODEL_COMMAND_PARSER
      - MODEL_CONFIRMATION_INTERPRETER=$MODEL_CONFIRMATION_INTERPRETER
      - MODEL_CORRECTION_PROCESSOR=$MODEL_CORRECTION_PROCESSOR
      - MODEL_CONTEXTUAL_CORRECTION_PROCESSOR=$MODEL_CONTEXTUAL_CORRECTION_PROCESSOR
      - MODEL_FUNCTION_CREATOR=$MODEL_FUNCTION_CREATOR
      - MODEL_JSON_FORMATTER=$MODEL_JSON_FORMATTER
      - MODEL_REACT_PLAN=$MODEL_REACT_PLAN
      - MODEL_REACT_EXIT_STRATEGY=$MODEL_REACT_EXIT_STRATEGY
      - MODEL_REACT_OBSERVE=$MODEL_REACT_OBSERVE
      - CONFIRM_TIMEOUT_SEC=$CONFIRM_TIMEOUT_SEC
      - INVENTORY_API_BASE_URL=$INVENTORY_API_BASE_URL
      - ENCRYPTION_PASSWORD=$ENCRYPTION_PASSWORD
      - EXIT_ON_MODEL_VALIDATION_FAILURE=$EXIT_ON_MODEL_VALIDATION_FAILURE
    volumes:
      - ./agent-server/logs:/app/logs
      - ./agent-server/user:/app/user
      - ./agent-server/firebase:/app/firebase
    ports:
      - "127.0.0.1:${WS_PORT:-12346}:${WS_PORT:-12346}"
    networks:
      - obsidian_network

  conversationalist:
    image: registry.alanhoangnguyen.com/admin/conversationalist:${CONVERSATIONALIST_VERSION:-latest}
    restart: unless-stopped
    environment:
      - FIREWORKS_API_KEY=$FIREWORKS_API_KEY
    networks:
      - obsidian_network

  open-webui:
    image: registry.alanhoangnguyen.com/admin/openwebui-monolithic:${OPENWEBUI_VERSION:-latest}
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://conversationalist:8080
      - CONVERSATIONALIST_BASE_URL=http://conversationalist:8080
      - PUBLIC_CONVERSATIONALIST_BASE_URL=http://conversationalist:8080
    volumes:
      - ./dev/open-webui:/app/backend/data
    networks:
      - obsidian_network

  nginx_proxy_manager:
    image: "happydance/nginx:latest"
    container_name: nginx_proxy_manager
    restart: unless-stopped
    networks:
      - obsidian_network
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - AGENT_SERVER_PORT=$AGENT_SERVER_REST_PORT
    volumes:
      - ./custom_server.conf:/etc/nginx/conf.d/custom_server.conf
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./npm/log:/var/log/nginx
      - ./dev/.htpasswd:/etc/nginx/.htpasswd
      - ./webroot:/var/www/certbot
    depends_on:
      - certbot

  docker-registry:
    image: registry:2
    container_name: docker_registry
    restart: unless-stopped
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/auth:/auth
    networks:
      - obsidian_network

  pypi-server:
    image: pypiserver/pypiserver:latest
    container_name: pypi-server
    restart: unless-stopped
    volumes:
      - ./pypi-server/packages:/data/packages
      - ./pypi-server/auth:/data/auth
    command: run -p 8080 -a update -P /data/auth/.htpasswd /data/packages
    networks:
      - obsidian_network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/certbot
      - ./certbot-scripts:/scripts
    environment:
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - DOMAINS=$CERTBOT_DOMAINS
    entrypoint: /bin/sh
    command: >
      -c "
      trap exit TERM;
      while :; do
        sleep 12h & wait;
        /scripts/renew-certs.sh;
      done"
    restart: unless-stopped
    networks:
      - obsidian_network

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard_server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: "1"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Denver}
      - SERVERURL=${SERVERURL}
      - SERVERPORT=${SERVERPORT:-51820}
      - PEERS=${PEERS:-1}
      - PEERDNS=${PEERDNS:-auto}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    networks:
      - obsidian_network
    ports:
      - "${SERVERPORT:-51820}:${SERVERPORT:-51820}/udp"
    restart: unless-stopped

  scheduler:
    image: happydance/scheduler:latest
    container_name: scheduler
    environment:
      - REST_ADDRESS=${SCHEDULER_REST_ADDRESS:-0.0.0.0}
      - REST_PORT=${SCHEDULER_PORT:-8080}
      - HELPER_URL=http://helper:8080
      - SCHEDULER_STORAGE_PATH=/app/data/scheduler_tasks.json
    volumes:
      - ./scheduler_data:/app/data
    networks:
      - obsidian_network
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - WEBHOOK_URL=${WEBHOOK_URL}
    networks:
      - obsidian_network
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./vaultwarden/vw-data:/data
    environment:
      - DOMAIN=${VAULTWARDEN_DOMAIN}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - SHOW_PASSWORD_HINT=false
      - WEB_VAULT_ENABLED=true
      - LOG_LEVEL=info
    networks:
      - obsidian_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  obsidian_network:
