version: '3'

services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    networks:
      - obsidian_network
    volumes:
      - $OBSIDIAN_VAULTS:/vaults
      - $OBSIDIAN_CONFIG:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - DOCKER_MODS=linuxserver/mods:universal-git

  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    networks:
      - obsidian_network
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./custom_server.conf:/etc/nginx/conf.d/custom_server.conf
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./npm/log:/var/log/nginx
      - ./.htpasswd:/etc/nginx/.htpasswd 


networks:
  obsidian_network:

