version: '3'

services:
  organizerserver:
    image: happydance/organizerserver:latest
    environment:
      - BASE_GIT_REPO_LOCATION=$BASE_GIT_REPO_LOCATION_CONTAINER
      - GIT_TOKEN=$GIT_TOKEN
      - GIT_USER=$GIT_USER
      - NOTE_BASE_LOCATION=$NOTE_BASE_LOCATION_CONTAINER
      - OBSIDIAN_VAULT_REPO_LOCATION=$OBSIDIAN_VAULT_REPO_LOCATION_CONTAINER
    volumes:
      - $OBSIDIAN_VAULT_LOCATION_HOST:$OBSIDIAN_VAULT_LOCATION_CONTAINER
    networks:
      - obsidian_network

  updater:
    image: happydance/updater:latest
    environment:
      - VAULT_LOCATION=/app/vault
      - USERNAME=$GUSERNAME
      - PASSWORD=$GPASSWORD
      - TOKEN=$GTOKEN
      - OUTPUT_PATH=/app/output
    volumes:
      - $OBSIDIAN_VAULTS:/app/vault

  agent-server:
    image: happydance/agent-server:latest
    restart: unless-stopped
    environment:
      - ORGANIZER_SERVER_URL=http://organizerserver:8080
      - REST_ADDRESS=$AGENT_SERVER_REST_ADDRESS
      - REST_PORT=$AGENT_SERVER_REST_PORT
      - FIREWORKS_API_KEY=$FIREWORKS_API_KEY
    networks:
      - obsidian_network

  translator:
    image: happydance/translator:latest
    restart: unless-stopped
    environment:
      - FIREWORKS_API_KEY=$FIREWORKS_API_KEY
    networks:
      - obsidian_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://translator:8080
    volumes:
      - ./dev/open-webui:/app/backend/data
    networks:
      - obsidian_network

  nginx_proxy_manager:
    image: 'happydance/nginx:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    networks:
      - obsidian_network
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - AGENT_SERVER_PORT=$AGENT_SERVER_REST_PORT
    volumes:
      - ./custom_server.conf:/etc/nginx/conf.d/custom_server.conf
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./npm/log:/var/log/nginx
      - ./dev/.htpasswd:/etc/nginx/.htpasswd

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard_server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: "1"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/Denver}
      - SERVERURL=${SERVERURL}
      - SERVERPORT=${SERVERPORT:-51820}
      - PEERS=${PEERS:-1}
      - PEERDNS=${PEERDNS:-auto}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    networks:
      - obsidian_network
    ports:
      - "${SERVERPORT:-51820}:${SERVERPORT:-51820}/udp"
    restart: unless-stopped


networks:
  obsidian_network:
