version: '3'

services:
  organizerserver:
    image: happydance/organizerserver:latest
    environment:
      - OBSIDIAN_VAULT_REPO_LOCATION=/app/vault
    volumes:
      - $OBSIDIAN_VAULTS/Organizer:/app/vault
    networks:
      - obsidian_network

  updater:
    image: happydance/updater:latest
    environment:
      - VAULT_LOCATION=/app/vault
      - USERNAME=$GUSERNAME
      - PASSWORD=$GPASSWORD
      - TOKEN=$GTOKEN
      - OUTPUT_PATH=/app/output
    volumes:
      - $OBSIDIAN_VAULTS:/app/vault

  agent-server:
    image: happydance/agent-server:latest
    restart: unless-stopped
    environment:
      - API_URL=https://api.openai.com/v1/chat/completions
      - LLM_TYPE=ChatGPT
      - ORGANIZER_SERVER_URL=http://organizerserver:8080
      - REST_ADDRESS=$AGENT_SERVER_REST_ADDRESS
      - REST_PORT=$AGENT_SERVER_REST_PORT
      - FIREWORKS_API_KEY=$FIREWORKS_API_KEY
    networks:
      - obsidian_network

  translator:
    image: happydance/translator:latest
    restart: unless-stopped
    environment:
      - FIREWORKS_API_KEY=$FIREWORKS_API_KEY
    networks:
      - obsidian_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://translator:8080
    volumes:
      - ./dev/open-webui:/app/backend/data
    networks:
      - obsidian_network

  nginx_proxy_manager:
    image: 'happydance/nginx:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    networks:
      - obsidian_network
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      - AGENT_SERVER_PORT=$AGENT_SERVER_REST_PORT
    volumes:
      - ./custom_server.conf:/etc/nginx/conf.d/custom_server.conf
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - ./npm/log:/var/log/nginx
      - ./dev/.htpasswd:/etc/nginx/.htpasswd

networks:
  obsidian_network:
